### ISSUE TITLE
Missing css properties

### ISSUE THREAD

**Issue by sarjanen** [johanholmerin/style9#15]
Hello!
Awesome library, just trying it out. Just noticed that not all css properties is supported, like listStyle and borderTopStyle. How to fix that?

EDIT

Looks like background doesn't work either, or am I doing something wrong here?
![image](https://user-images.githubusercontent.com/814347/96120490-dd231000-0eee-11eb-898f-acefb2f7f564.png)

**Comment by johanholmerin** [comment]
`listStyle` and `background` are both shorthands. Because of how style9 merges style definitions, only longhand properties are supported, with a few exceptions which can be expanded automatically(e.g. `borderStyle`). You can use `list-style-type` and `background-*` instead. I'll update the README to clarify.

That `borderTopStyle` is missing is a bug. I've fixed it in `0.5.6`.
