### ISSUE TITLE
grid-area

### ISSUE THREAD

**Issue by fshowalter** [johanholmerin/style9#27]
Possible for an easier implementation for named grid areas? I get that it's a shorthand property for `grid-column-end`,
`grid-column-start`, `grid-row-end`, `grid-row-start`, and it would be hard to support the non-named version (i.e. something like `grid-area: 2 / 1 / 2 / 4;`) but expanding named grid-areas would be a boon.

**Comment by johanholmerin** [comment]
I think [inline-style-expand-shorthand](https://github.com/robinweser/inline-style-expand-shorthand) is a better place for this, since that would benefit all users. If the project is dead I would be open to switching to a fork, but I don't think that would be necessary. It's not being actively develop, but I believe a PR would be merged promptly.
