### ISSUE TITLE
Generate readable class names in output

### ISSUE THREAD

**Issue by redbar0n** [johanholmerin/style9#31]
You wrote:
> Some may complain about this, that the generated class names are not semantic, that they are opaque and are ignoring the cascade. This is true.

In: https://css-tricks.com/style9-build-time-css-in-js/

I just thought I'd mention the idea I came across in the video from Stitches, that unreadable class names could potentially be overcome in the build output.

Inspired by Stitches: https://youtu.be/Gw28VgyKGkw?t=2061

**Comment by johanholmerin** [comment]
It's definitely something that would be interesting to add. The way stitches does it wouldn't quite work, since style9 generates atomic CSS, and adding a readable name to each property wouldn't be very helpful. What you would want is a name for each object in `style9.create`, and some way to toggle all the applied properties in dev tools. How to achieve that is unclear at the moment. It would require changing both the generated Javascript and CSS in development.

I'm closing this issue for the moment, but expect to come back to it at some point. Feel free to add any additional comments or ideas.
