### ISSUE TITLE
Support for advanced pseudos

### ISSUE THREAD

**Issue by Dwlad90** [johanholmerin/style9#64]
I'd like to ask are you can to add support for advanced pseudos like :not, :nth-child etc?

**Comment by johanholmerin** [comment]
One of the principles of style9 is that unlike plain CSS, what properties get applied to an element should be clear from the definition. Media queries and simple pseudo selectors can cause confusion, but because they are so essential and because they can be made somewhat more deterministic through post-process sorting, they are supported anyway. It is however something that I would like to keep to a minimum and not expand support for. If you do wish to use advanced pseudo selectors yourself, there is nothing in the compiler that prevents it, it's only the TypeScript definitions that lack them. You could suppress the type errors, cast the values, or possibly augment the TypeScript interfaces.

**Comment by Dwlad90** [comment]
Thanks a lot for a suggestion! I really appreciate that
